Traceback (most recent call last):
  File "C:\Users\julia\miniconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\julia\miniconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\julia\miniconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\julia\miniconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\julia\miniconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\julia\miniconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\julia\miniconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\julia\miniconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Adding a new friend to our notebook:
key_list = list(notebook.keys())
i = 0
for entry in notebook.values():
    print("Please add a new", key_list[i])
    new_entry = input()
    entry.append(new_entry)
    i += 1
print(notebook)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_5212\3349261285.py[0m in [0;36m<module>[1;34m[0m
[0;32m      4[0m [1;32mfor[0m [0mentry[0m [1;32min[0m [0mnotebook[0m[1;33m.[0m[0mvalues[0m[1;33m([0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m     [0mprint[0m[1;33m([0m[1;34m"Please add a new"[0m[1;33m,[0m [0mkey_list[0m[1;33m[[0m[0mi[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 6[1;33m     [0mnew_entry[0m [1;33m=[0m [0minput[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      7[0m     [0mentry[0m[1;33m.[0m[0mappend[0m[1;33m([0m[0mnew_entry[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m     [0mi[0m [1;33m+=[0m [1;36m1[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\miniconda3\lib\site-packages\ipykernel\kernelbase.py[0m in [0;36mraw_input[1;34m(self, prompt)[0m
[0;32m   1070[0m         """
[0;32m   1071[0m         [1;32mif[0m [1;32mnot[0m [0mself[0m[1;33m.[0m[0m_allow_stdin[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1072[1;33m             raise StdinNotImplementedError(
[0m[0;32m   1073[0m                 [1;34m"raw_input was called, but this frontend does not support input requests."[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1074[0m             )

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

